[project]
name = "opfo"
version = "0.1.0"
description = "opfo OverPowerdFileOrganizer is an advanced file organizer implemented in python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
]
